apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongo
  serviceName: mongo-headless
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:7.0.5
          imagePullPolicy: Always
          {{- if .Values.mongo.resources }}
          resources: {{- toYaml .Values.mongo.resources | nindent 12 }}
          {{- else if ne .Values.mongo.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.mongo.resourcesPreset ) | nindent 12 -}}
          {{- end }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username | required "mongo.username is required" }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretKeyName | required "mongo.secretKeyName is required" }}
                  key: rootPassword
            {{- if .Values.mongo.env }}
            {{- toYaml .Values.mongo.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
              readOnly: false
              subPath: ''
          ports:
            - name: mongo-port
              containerPort: 27017
      terminationGracePeriodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: mongo
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.mongo.storageSize | quote }}
