apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo-service
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
