{{- $secretName := "seaweedfs-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $secretName }}
type: Opaque
data:
  {{- $rootPassword := include "common.secrets.generate" (dict "devDefault" "example" "context" $) }}
  rootPassword: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "rootPassword" "defaultValue" $rootPassword "context" $) }}
