apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backend
  name: backend-headless
spec:
  clusterIP: None
  ports:
  - name: web
    port: 80
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: devspace-app
