apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  externalIPs: null
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: queue
    port: {{ .Values.queue.port }}
    protocol: TCP
    targetPort: {{ .Values.queue.port }}
  {{- if .Values.configuration.devmode }}
  - name: debug
    port: 5678
    targetPort: 5678
    protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/component: backend
  type: ClusterIP
