apiVersion: v1
kind: Secret
metadata:
  name: "mongo-default-secret"
type: Opaque
data:
  {{- if not .Values.configuration.devmode }}

  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "mongo-default-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  # Helm does not allow hypen character, as a variable name , so we conform to camelCase
  {{- $mongoPassSecret_env := (get $secretData "mongo-password-secret") | default (randAlphaNum 32 | b64enc) }}
  mongo-password-secret: {{ $mongoPassSecret_env | quote }}

  {{- else }}

  mongo-password-secret: {{ "example" | b64enc }}  # Base64-encoded "example"

  {{- end }}