apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: mongo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: devspace-app
  name: mongo
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mongo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: devspace-app
  serviceName: mongo-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: devspace-app
    spec:
      affinity: null
      containers:
      - args: null
        command: null
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.db.mongo.settings.mongoUsername }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.db.mongo.mongosecret }}
              key: mongo-password-secret
        envFrom: null
        image: mongo:7.0.3
        lifecycle: null
        livenessProbe: null
        name: container-0
        readinessProbe: null
        securityContext: null
        startupProbe: null
        volumeDevices: null
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
          readOnly: false
          subPath: ''
      dnsConfig: null
      ephemeralContainers: null
      hostAliases: null
      imagePullSecrets: null
      initContainers: null
      nodeName: null
      nodeSelector: null
      overhead: null
      readinessGates: null
      securityContext: null
      terminationGracePeriodSeconds: 5
      tolerations: null
      topologySpreadConstraints: null
      volumes: null
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/component: mongo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: devspace-app
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
