apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5800
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: registry
