apiVersion: v1
kind: Secret
metadata:
  name: "seaweedfsecret"
type: Opaque
data:
  {{- if not .Values.configuration.devmode }}

  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "seaweedfsecret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}


  {{- $S3_ROOT_PWD_SECRET_env := (get $secretData "S3_ROOT_PWD_SECRET") | default (randAlphaNum 32 | b64enc) }}
  S3_ROOT_PWD_SECRET: {{ $S3_ROOT_PWD_SECRET_env | quote }}

  {{- else }}

  S3_ROOT_PWD_SECRET: {{ "admin" | b64enc }}  # Base64-encoded "admin"

  {{- end }}