apiVersion: v1
kind: Secret
metadata:
  name: "syftsecret"
type: Opaque
data:
  {{- if not .Values.configuration.devmode }}

  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "syftsecret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $stackApiKey_env := (get $secretData "stackApiKey") | default (randAlphaNum 32 | b64enc) }}
  stackApiKey: {{ $stackApiKey_env | quote }}

  {{- $defaultRootPassword_env := (get $secretData "defaultRootPassword") | default (randAlphaNum 32 | b64enc) }}
  defaultRootPassword: {{ $defaultRootPassword_env | quote }}

  {{- else }}
  stackApiKey: {{ "changeme" | b64enc }} # Base64-encoded "changeme"
  defaultRootPassword: {{ "changethis" | b64enc}} # Base64-encoded "changethis"
  {{- end }}