apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-builds
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: worker-builds
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    # k3d does not support ReadWriteMany
    {{- if .Values.configuration.devmode }}
    - ReadWriteOnce
    {{- else}}
    - ReadWriteMany
    {{- end}}
  resources:
    requests:
      storage: {{ .Values.workerBuilds.maxStorage }}
