version: "3.8"
services:
  frontend:
    build:
      context: ${RELATIVE_PATH}./frontend
      dockerfile: frontend.dockerfile
      target: "${FRONTEND_TARGET:-grid-ui-development}"
    profiles:
      - frontend

  backend:
    build:
      context: ${RELATIVE_PATH}../
      dockerfile: ./grid/backend/backend.dockerfile
      target: "backend"
    profiles:
      - backend

  seaweedfs:
    build:
      context: ${RELATIVE_PATH}./seaweedfs
      dockerfile: seaweedfs.dockerfile
      target: "seaweedfs"
      args:
        - DOCKER_IMAGE_SEAWEEDFS_ORIGINAL=${DOCKER_IMAGE_SEAWEEDFS_ORIGINAL}
        - SEAWEEDFS_VERSION=${SEAWEEDFS_VERSION}
    profiles:
      - blob-storage

  worker:
    build:
      context: ${RELATIVE_PATH}../
      dockerfile: ./grid/backend/backend.dockerfile
      target: "backend"
    profiles:
      - worker
