---
apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/chart: component-chart-0.8.6
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backend
  name: backend
spec:
  externalIPs: null
  ports:
    - name: port-0
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: devspace-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    helm.sh/chart: component-chart-0.8.6
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: devspace-app
  name: backend
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: devspace-app
  serviceName: backend-headless
  template:
    metadata:
      annotations:
        helm.sh/chart: component-chart-0.8.6
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: devspace-app
    spec:
      affinity: null
      containers:
        - args: null
          command: null
          env:
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: example
            - name: SERVICE_NAME
              value: backend
            - name: RELEASE
              value: production
            - name: VERSION
              value: 0.8.1-beta.11
            - name: VERSION_HASH
              value: unknown
            - name: NODE_TYPE
              value: domain
            - name: NODE_NAME
              value: default_node_name
            - name: STACK_API_KEY
              value: changeme
            - name: PORT
              value: "80"
            - name: IGNORE_TLS_ERRORS
              value: "False"
            - name: HTTP_PORT
              value: "80"
            - name: HTTPS_PORT
              value: "443"
            - name: CONTAINER_HOST
              value: k8s
            - name: TRACE
              value: "False"
            - name: JAEGER_HOST
              value: localhost
            - name: JAEGER_PORT
              value: "14268"
            - name: DEV_MODE
              value: "False"
            - name: DOMAIN_CONNECTION_PORT
              value: "3030"
            - name: ENABLE_OBLV
              value: "false"
            - name: DEFAULT_ROOT_EMAIL
              value: info@openmined.org
            - name: DEFAULT_ROOT_PASSWORD
              value: changethis
            - name: BACKEND_STORAGE_PATH
              value: /storage
          envFrom: null
          image: docker.io/openmined/grid-backend:0.8.1-beta.11
          lifecycle: null
          livenessProbe: null
          name: container-0
          readinessProbe: null
          securityContext: null
          startupProbe: null
          volumeDevices: null
          volumeMounts:
            - mountPath: /storage
              name: credentials-data
              readOnly: false
              subPath: credentials-data
      dnsConfig: null
      ephemeralContainers: null
      hostAliases: null
      imagePullSecrets: null
      initContainers: null
      nodeName: null
      nodeSelector: null
      overhead: null
      readinessGates: null
      securityContext: null
      terminationGracePeriodSeconds: 5
      tolerations: null
      topologySpreadConstraints: null
      volumes: null
  volumeClaimTemplates:
    - metadata:
        annotations:
          helm.sh/chart: component-chart-0.8.6
        labels:
          app.kubernetes.io/component: backend
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: devspace-app
        name: credentials-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
