apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-service-secret
  annotations:
    kubernetes.io/service-account.name: "backend-service-account"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-service-secret
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-service-role
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-service-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-service-role-binding
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-service-role-binding
subjects:
  - kind: ServiceAccount
    name: backend-service-account
roleRef:
  kind: Role
  name: backend-service-role
  apiGroup: rbac.authorization.k8s.io
