apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-service
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
    - name: queue
      protocol: TCP
      port: {{ .Values.node.queuePort }}
      targetPort: {{ .Values.node.queuePort }}
