global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  level: INFO

entryPoints:
  web:
    address: :80
    transport:
      respondingTimeouts:
        tcp:
          lingeringTimeout: 0
  ping:
    address: :8082

ping:
  entryPoint: "ping"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
