apiVersion: v1
entries:
  syft:
  - apiVersion: v2
    appVersion: 0.8.2-beta.12
    created: "2023-08-15T05:52:13.86656919Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 4fc88c5d3cca5e72f0cef69d3ae7b34ba588740f1d3134cdd6fd6f05f9fd984d
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.12.tgz
    version: 0.8.2-beta.12
  - apiVersion: v2
    appVersion: 0.8.2-beta.11
    created: "2023-08-15T05:52:13.866068244Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 8ba00feb3c41d26c3bce5bd563812976e0fd382db7b5a7dd0c94527b5a82bc63
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.11.tgz
    version: 0.8.2-beta.11
  - apiVersion: v2
    appVersion: 0.8.2-beta.10
    created: "2023-08-15T05:52:13.865565626Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: a0e9ac14c466e5bc0b19459024710a629b8d67defa8ef43aa99b547b5204e378
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.10.tgz
    version: 0.8.2-beta.10
  - apiVersion: v2
    appVersion: 0.8.2-beta.9
    created: "2023-08-15T05:52:13.871269287Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 8c224c4833f0f380442395af0a09d507b605f5642bb376a3f4a8fbb8dec38eb7
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.9.tgz
    version: 0.8.2-beta.9
  - apiVersion: v2
    appVersion: 0.8.2-beta.8
    created: "2023-08-15T05:52:13.870733377Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: c286a429e94e7098ba1f9854536741b247ae3d00f4ec0c2458cdfb405c2720e1
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.8.tgz
    version: 0.8.2-beta.8
  - apiVersion: v2
    appVersion: 0.8.2-beta.7
    created: "2023-08-15T05:52:13.870229677Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: e52ce2d32a90f1c181e42c01970b637e78f64cf6e70daca22b2765f6aa89e2c3
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.7.tgz
    version: 0.8.2-beta.7
  - apiVersion: v2
    appVersion: 0.8.2-beta.6
    created: "2023-08-15T05:52:13.8697114Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: b764c5515e5ebc76aea36d59022ca451d840a88d8e47057c64528ae8827ffcd6
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.6.tgz
    version: 0.8.2-beta.6
  - apiVersion: v2
    appVersion: 0.8.2-beta.5
    created: "2023-08-15T05:52:13.869187722Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: bad9095fc119e545fdb76bd13680b10443e2989de562fe9483517214419138a8
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.5.tgz
    version: 0.8.2-beta.5
  - apiVersion: v2
    appVersion: 0.8.2-beta.4
    created: "2023-08-15T05:52:13.868054191Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 8f58e7e654dc0005d2d1b6ddafe6ba7a4fc3e1d987c3f6dd09acced56c7a9ea6
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.4.tgz
    version: 0.8.2-beta.4
  - apiVersion: v2
    appVersion: 0.8.2-beta.3
    created: "2023-08-15T05:52:13.867556362Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 6d313cf2128768b74596d8dea74c53146fe063f90d0c6ffe8d5990d738290b59
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.3.tgz
    version: 0.8.2-beta.3
  - apiVersion: v2
    appVersion: 0.8.2-beta.2
    created: "2023-08-15T05:52:13.867063141Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: d2a7c88a73ef9e70237844cb8628c82262291352f95bbed434c574c2b6362432
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.2.tgz
    version: 0.8.2-beta.2
  - apiVersion: v2
    appVersion: 0.8.2-beta.1
    created: "2023-08-15T05:52:13.865077956Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 53e23cb249cdb9d77c0bc2ed9f1a3173e28421297c02aa53ed0c0aaf0476257a
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.1.tgz
    version: 0.8.2-beta.1
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2023-08-15T05:52:13.864562594Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: d347f1c199309282b7451da10560b79d244c78cad33c8ba5c1337ac626446927
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: 0.8.1-beta.21
    created: "2023-08-15T05:52:13.864062491Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: fb923353dd4195b2a6bee804c421f1565cb8a3ad95e5bb3df1b0b882a21bc4ef
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.21.tgz
    version: 0.8.1-beta.21
  - apiVersion: v2
    appVersion: 0.8.1-beta.20
    created: "2023-08-15T05:52:13.863551226Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: ec977f97cff09c509594cb211f118ea28cd95bb8b07e4e5b65409decc2e3bc4c
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.20.tgz
    version: 0.8.1-beta.20
  - apiVersion: v2
    appVersion: 0.8.1-beta.19
    created: "2023-08-15T05:52:13.863041775Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 258e31f7b9876a0265bcafb2b4044be5b1d62b08089ed19f071817f0b1ba5f6d
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.19.tgz
    version: 0.8.1-beta.19
  - apiVersion: v2
    appVersion: 0.8.1-beta.15
    created: "2023-08-15T05:52:13.862516725Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 761dc6a54d5b288a94c6fb088d2251a4ce213db06710ac19bc1e81d40d49e94c
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.15.tgz
    version: 0.8.1-beta.15
  - apiVersion: v2
    appVersion: 0.8.1-beta.12
    created: "2023-08-15T05:52:13.861959806Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 84c577fa6a40fe53d32fc91ef4a28c89486f78f5f07856ee81fba5dc7118507d
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.12.tgz
    version: 0.8.1-beta.12
generated: "2023-08-15T05:52:13.861240263Z"
