apiVersion: v1
entries:
  syft:
  - apiVersion: v2
    appVersion: 0.8.1-beta.15
    created: "2023-06-22T15:51:30.941896+10:00"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 761dc6a54d5b288a94c6fb088d2251a4ce213db06710ac19bc1e81d40d49e94c
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.15.tgz
    version: 0.8.1-beta.15
  - apiVersion: v2
    appVersion: 0.8.1-beta.12
    created: "2023-06-22T15:51:30.941521+10:00"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 84c577fa6a40fe53d32fc91ef4a28c89486f78f5f07856ee81fba5dc7118507d
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1-beta.12.tgz
    version: 0.8.1-beta.12
generated: "2023-06-22T15:51:30.940764+10:00"
