{{- $secretName := "seaweedfs-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $secretName }}
type: Opaque
data:
  {{- $s3Password := include "common.secrets.generate" (dict "devDefault" "admin" "context" $) }}
  s3RootPassword: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "s3RootPassword" "defaultValue" $s3Password "context" $) }}
