{{- if ne .Values.node.type "gateway"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: seaweedfs
data:
  {{- if .Values.seaweedfs.master.config }}
  master.toml: |
    # User provisioned master config
    {{ .Values.seaweedfs.master.config | nindent 4 }}
    # End master config
  {{- end }}

  {{- if .Values.seaweedfs.filer.config }}
  filer.toml: |
    # User provisioned filer config
    {{ .Values.seaweedfs.filer.config | nindent 4 }}
    # End filer config
  {{- end }}

  {{- if .Values.seaweedfs.mountApi.autoMountConfig }}
  automount.yaml: |
    # User provisioned automount config
    {{ .Values.seaweedfs.mountApi.autoMountConfig | nindent 4 }}
    # End automount config
  {{- end }}

{{ end }}
