{{- if ne .Values.node.type "gateway"}}
{{- $secretName := "seaweedfs-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: seaweedfs
type: Opaque
data:
  {{- $s3Password := include "common.secrets.generate" (dict "default" .Values.seaweedfs.defaultSecret.s3RootPassword "context" $) }}
  s3RootPassword: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "s3RootPassword" "value" $s3Password "context" $) }}
{{ end }}
