http:
  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
    backend:
      loadBalancer:
        servers:
          - url: "http://proxy:8001"
    backend-stream:
      loadBalancer:
        servers:
          - url: "http://proxy:8011"
    seaweedfs:
      loadBalancer:
        servers:
          - url: "http://seaweedfs:8333"
    seaweedfsmount:
      loadBalancer:
        servers:
          - url: "http://seaweedfs:4001"
    rathole:
      loadBalancer:
        servers:
          - url: "http://rathole:5555"
    ratholeforward:
      loadBalancer:
        servers:
          - url: "http://rathole:8000"
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: "frontend"
    backend:
      rule: "PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
      entryPoints:
        - web
      service: "backend"
    backend-stream:
      rule: "PathPrefix(`/api`) && PathPrefix(`/api/v1/syft/stream`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
      entryPoints:
        - web
      service: "backend-stream"
    blob-storage:
      rule: "PathPrefix(`/blob`)"
      entryPoints:
        - web
      service: "seaweedfs"
      middlewares:
        - "blob-storage-url"
        - "blob-storage-host"
    rathole:
      rules: "PathPrefix(`/rathole`)"
      entryPoints:
        - web
      service: "rathole"
      middlewares:
        - "rathole-url"
    ratholeforward:
      rules: "HostRegexp(`{subdomain:[a-z]+}.local.rathole`)"
      entryPoints:
        - web
      service: "ratholeforward"
      # middlewares:
      #   - "rathole-redirect"
    ping:
      rule: "PathPrefix(`/ping`)"
      entryPoints:
        - web
      service: "ping@internal"

  middlewares:
    # by rewriting the customrequestheaders.Host with the same host:port as the
    # code uses internally any S3 presigned urls will still validate
    blob-storage-host:
      headers:
        customrequestheaders:
          Host: seaweedfs:8333
    blob-storage-url:
      stripprefix:
        prefixes: /blob
        forceslash: true
    rathole-url:
      stripprefix:
        prefixes: /rathole
        forceslash: true
    rathole-redirect:
      redirectregex:
        regex: "^.+"
        replacement: "http://rathole:8000$${1}"
        permanent: true
