global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog: {}

log:
  level: INFO

entryPoints:
  web:
    address: :81
    transport:
      respondingTimeouts:
        tcp:
          lingeringTimeout: 0

ping:
  manualRouting: true

providers:
  file:
    directory: /etc/traefik/conf
    watch: true
