apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rathole
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: rathole
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rathole
  serviceName: rathole
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: rathole
        {{- if .Values.reverse_tunnel.podLabels }}
        {{- toYaml .Values.reverse_tunnel.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.reverse_tunnel.podAnnotations }}
      annotations: {{- toYaml .Values.reverse_tunnel.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.reverse_tunnel.nodeSelector }}
      nodeSelector: {{- .Values.reverse_tunnel.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: rathole
        image: {{ .Values.global.registry }}/openmined/grid-rathole:{{ .Values.global.version }}
        imagePullPolicy: Always
        resources: {{ include "common.resources.set" (dict "resources" .Values.reverse_tunnel.resources "preset" .Values.reverse_tunnel.resourcesPreset) | nindent 12 }}
        env:
            - name: LOG_LEVEL
              value: {{ .Values.reverse_tunnel.logLevel | quote }}
            - name: MODE
              value: {{ .Values.reverse_tunnel.mode | quote }}
            - name: RATHOLE_PORT
              value: {{ .Values.reverse_tunnel.port | quote }}
            {{- if .Values.reverse_tunnel.env }}
            {{- toYaml .Values.reverse_tunnel.env | nindent 12 }}
            {{- end }}
        ports:
          - name: rathole-port
            containerPort: 2333
        startupProbe: null
        livenessProbe: null
        volumeMounts:
          - name: mount-config
            mountPath: /conf/
            readOnly: false
          - name: rathole-config
            mountPath: /app/conf/
            readOnly: false
      terminationGracePeriodSeconds: 5
      volumes:
        - name: rathole-config
          emptyDir: {}
        - name: mount-config
          configMap:
            name: rathole-config
  volumeClaimTemplates:
  - metadata:
      name: rathole-data
      labels:
        {{- include "common.volumeLabels" . | nindent 8 }}
        app.kubernetes.io/component: rathole
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi