apiVersion: v1
kind: ConfigMap
metadata:
  name: rathole-config
  resourceVersion: ""
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: rathole
data:
  {{- if eq .Values.rathole.mode "server" }}
  server.toml: |
    [server]
    bind_addr = "0.0.0.0:2333"

    [server.transport]
    type = "websocket"
    [server.transport.websocket]
    tls = false

    [server.services.domain]
    token = "domain-specific-rathole-secret"
    bind_addr = "0.0.0.0:8001"
  {{- end }}

  {{- if eq .Values.rathole.mode "client" }}
  client.toml: |
    [client]
    remote_addr = "0.0.0.0:2333"

    [client.transport]
    type = "websocket"
    [client.transport.websocket]
    tls = false
  {{- end }}
