apiVersion: v1
kind: Service
metadata:
  name: rathole
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: rathole
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rathole
  ports:
    - name: rathole
      protocol: TCP
      port: 2333
      targetPort: 2333
