apiVersion: v1
kind: ConfigMap
metadata:
  name: rathole-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: rathole
data:
  {{- if eq .Values.rathole.mode "server" }}
  server.toml: |
    [server]
    bind_addr = "0.0.0.0:2333"
  {{- end }}

  {{- if eq .Values.rathole.mode "client" }}
  client.toml: |
    [client]
    remote_addr = ""
