# Default values for syft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secrets:
  syft:
    syftsecret: "syftsecret"
    # stackApiKey: "changeme"
    # defaultRootEmail: "info@openmined.org"
    # defaultRootPassword: "changethis"
  db:
    mongo:
      # mongoPassword: "example"
      # mongoInitdbRootPassword: "example"
      # mongoUsername: "root"
      # mongoInitdbRootUsername: "root"
      mongosecret: "mongosecret"

configuration:
  devmode: false

db:
  mongo:
    settings:
      mongoPort: "'27017'"
      mongoHost: "mongo"

node:
  settings:
    tls: false
    hostname: "" # do not make this localhost
    nodeName: "mynode"
    nodeType: "domain"
    versionHash: "abc"

ingress:
  ingressClass: ""
  # ingressClass: "azure/application-gateway"
  # ingressClass: "gce"
