# Default values for syft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secrets:
  syft: syft-default-secret
  mongo: mongo-default-secret
  seaweedfs: seaweedfs-default-secret

configuration:
  devmode: false

db:
  mongo:
    settings:
      mongoPort: "'27017'"
      mongoHost: "mongo"
      mongoUsername: "root"

seaweedfs:
  S3_VOLUME_SIZE_MB: 1024
  S3_PORT: 8333
  SEAWEED_MOUNT_PORT: 4001
  S3_ROOT_USER: "admin"

container:
  registry: "docker.io"
  syft_version: 0.8.4-beta.3

node:
  settings:
    tls: false
    hostname: "" # do not make this localhost
    nodeName: "mynode"
    nodeType: "domain"
    versionHash: "abc"
    nodeSideType: "high"
    defaultRootEmail: "info@openmined.org"

ingress:
  ingressClass: ""
  # ingressClass: "azure/application-gateway"
  # ingressClass: "gce"
