# Default values for syft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secrets:
  syft:
    stackApiKey: "changeme"
    defaultRootEmail: "info@openmined.org"
    defaultRootPassword: "changethis"
  db:
    mongo:
      mongoPassword: "example"
      mongoInitdbRootPassword: "example"
      mongoUsername: "root"
      mongoInitdbRootUsername: "root"

db:
  mongo:
    settings:
      mongoPort: "'27017'"
      mongoHost: "mongo"

container:
  registry: "docker.io"
  syft_version: 0.8.3-beta.5

node:
  settings:
    tls: false
    hostname: "" # do not make this localhost
    nodeName: "mynode"
    nodeType: "domain"
    versionHash: "abc"
    nodeSideType: "high"

ingress:
  ingressClass: ""
  # ingressClass: "azure/application-gateway"
  # ingressClass: "gce"
