global:
  registry: docker.io
  version: 0.8.5-beta.1
  devmode: false

mongo:
  port: 27017
  host: mongo
  username: root
  secretKeyName: mongo-secret
  # pod resources
  resourcesPreset: nano
  resources: null
  # env vars
  extraEnvs: null

frontend:
  # pod resources
  resourcesPreset: nano
  resources: null
  # env vars
  extraEnvs: null

seaweedfs:
  # SeaweedFS config
  mountPort: 4001
  # SeaweedFS S3 Config
  s3VolumeSizeMB: 1024
  s3Port: 8333
  s3RootUser: admin
  # pvc storage limits
  maxStorage: 5Gi
  # secrets
  secretKeyName: seaweedfs-secret
  # resource limits
  resourcesPreset: nano
  resources: null

proxy:
  resourcesPreset: nano
  resources: null

registry:
  maxStorage: 10Gi
  resourcesPreset: nano
  resources: null

node:
  name: null
  rootEmail: info@openmined.org
  type: domain
  side: high
  inMemoryWorkers: false
  defaultWorkerPoolCount: 1
  queuePort: 5556
  logLevel: info
  oblv:
    enabled: false
    port: 3030
  secretKeyName: backend-secret
  extraEnvs: null
  resourcesPreset: small
  resources: null

# ----------------------------------------
# For Azure
# className: azure-application-gateway
# ----------------------------------------
# For AWS
# className: alb
# ----------------------------------------
# For GCE, https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#create-ingress
# class: gce
# ----------------------------------------
ingress:
  hostname: null # do not make this localhost
  tls:
    enabled: false
    secretName: null

  class: null
  className: null
