apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grid-stack-ingress
  annotations:
    kubernetes.io/ingress.class: ""
spec:
  defaultBackend:
    service:
      name: proxy
      port:
        number: 80
  tls:
    - hosts:
        - "example.com"
      # secretName: Add custom TLS secret here or default certificate is used
  rules:
    - host: "example.com"
      http:
        paths:
          - backend:
              service:
                name: proxy
                port:
                  number: 80
            path: /
            pathType: Prefix
